# Generated by Django 3.1.13 on 2021-08-28 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
