# Generated by Django 3.1.13 on 2021-09-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_modified_at_to_updated_at'),
        ('profiles', '0002_rename_modified_at_to_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(related_name='liked_authors', to='posts.Post'),
        ),
    ]
